parser: babel-eslint

parserOptions:
  ecmaVersion: 7
  sourceType: module

extends:
  - eslint:recommended
  - plugin:flowtype/recommended

plugins:
  - flowtype

env:
  browser: true
  node: true
  es6: true

rules:
  semi:
    - error
    - never
